### ISSUE TITLE
Set a meaningful User Agent

### ISSUE THREAD

**Issue by Leseratte10** [vilmarbfilho/Wiimmfi-App#18]
Right now your app seems to be using a standard browser User Agent to load the data from Wiimmfi: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36`

Would you mind using a more descriptive User Agent like `Wiimmfi-App v0.0.1 - Vilmar Filho - https://github.com/vilmarbfilho/Wiimmfi-App` to make it clear to the server (and to us admins when we view the logs) that these requests are coming from an inofficial app?

Thanks.

**Comment by vilmarbfilho** [comment]
Hello @Leseratte10 sure. In the next version I will change the User Agent, I thought in something like that `Wiimmfi-App/0.0.1 (Android) VilmarBFilho (https://github.com/vilmarbfilho/Wiimmfi-App)` what do tyou think?

**Comment by Leseratte10** [comment]
That's okay as well, it should just be something that identifies the App, the developer, and the Github or other contact URL.

**Comment by vilmarbfilho** [comment]
The user agent will follow the pattern:

`Wiimmfi-App/0.0.1 (Android 29; Xiaomi Mi A2) VilmarBFilho (https://github.com/vilmarbfilho/Wiimmfi-App)`

It will be available in the next generated version.
